# Markdown config
highlighter: rouge
name: USAJOBS Design System
subtitle: The design system for the next generation of USAJOBS which describes the base visual language upon which the site can be built.
exclude:
  - ".DS_Store"
  - ".jekyll-metadata"
  - ".publish"
  - ".sass-cache"
  - ".ruby-version"
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - ISSUE_TEMPLATE.md
  - LICENSE.md
  - npm-debug.log
  - node_modules
  - package.json
  - package-lock.json
  - README.md
keep_files: ["css", "js"]

# Creative Cloud uses port 4000? Setting a unique port number
port: 4001

#destination: ./_site
# layouts: ./_layouts
baseurl: "/design-system"

permalink: pretty

author:
  name: USAJOBS
  url: https://usajobs.github.io/

repository:
  name: Design System
  url: https://github.com/USAJOBS/design-system

# google_analytics_ua: UA-48605964-33

collections:
  components:
    output: true
    permalink: /:path/
  elements:
    output: true
    permalink: /:path/
  grid:
    output: true
    permalink: /:path/
  shell:
    output: true
    permalink: /:path/
  page-layouts:
    output: true
    permalink: /:path/
  visual:
    output: true
    permalink: /:path/
